package com.android.purebilibili

class MainActivitySplashBlueSnowMaid : MainActivity()
class MainActivitySplashBlueSnowMaidAnnouncement : MainActivity()
class MainActivitySplashBlueSnowMaidAnnouncementLight : MainActivity()
class MainActivitySplashBlueSnowMaidAnnouncementDark : MainActivity()
class MainActivitySplashBlueSnowMaidFront : MainActivity()
class MainActivitySplashBlueSnowMaidLight : MainActivity()
class MainActivitySplashBlueSnowMaidDark : MainActivity()
class MainActivitySplashBlueSnowMaidFrontLight : MainActivity()
class MainActivitySplashBlueSnowMaidFrontDark : MainActivity()
class MainActivitySplashIcon3D : MainActivity()
class MainActivitySplashBiliPai : MainActivity()
class MainActivitySplashBiliPaiPink : MainActivity()
class MainActivitySplashBiliPaiWhite : MainActivity()
class MainActivitySplashBiliPaiMonet : MainActivity()
class MainActivitySplashNoIcon : MainActivity()
