"""Build local layered-illustration Lottie timelines from the approved artwork.
Requires Pillow only. Creative artwork was generated by imagegen from the user's
reference; resizing is deterministic packaging, not a replacement illustration.
A single shared local bitmap preserves the reference's fine eye/lace shading;
independent eye/hand masks and vector effects provide the actual motion.
"""
import copy
import json
import math
from pathlib import Path
from PIL import Image
from package_assets import build_preview

ROOT = Path(__file__).resolve().parents[2]
ART = Path(__file__).parent

def prop(v): return {'a':0,'k':v}
def keys(values):
    out=[]
    for j,(t,v) in enumerate(values):
        d={'t':t,'s':v if isinstance(v,list) else [v]}
        if j<len(values)-1:
            end=values[j+1][1]
            d.update(e=end if isinstance(end,list) else [end],o={'x':[.23],'y':[1]},i={'x':[.32],'y':[1]})
        out.append(d)
    return {'a':1,'k':out}
def color(h): return [int(h[i:i+2],16)/255 for i in (1,3,5)]+[1]
def xy(z): return [round(z.real,2),round(z.imag,2)]
def transform(): return {'ty':'tr','p':prop([0,0]),'a':prop([0,0]),'s':prop([100,100]),'r':prop(0),'o':prop(100),'sk':prop(0),'sa':prop(0)}
def group(name,geometries,fill=None,stroke=None,width=2):
    it=list(geometries)
    if fill: it.append({'ty':'fl','c':prop(color(fill)),'o':prop(100),'r':1})
    if stroke: it.append({'ty':'st','c':prop(color(stroke)),'o':prop(100),'w':prop(width),'lc':2,'lj':2})
    it.append(transform()); return {'ty':'gr','nm':name,'it':it}
def poly(points,closed=True):
    return {'v':points,'i':[[0,0] for _ in points],'o':[[0,0] for _ in points],'c':closed}
def shape(points,closed=True): return {'ty':'sh','ks':prop(poly(points,closed))}
def ellipse(x,y,w,h): return {'ty':'el','p':prop([x,y]),'s':prop([w,h]),'d':1}
def rect(x,y,w,h,r=6): return {'ty':'rc','p':prop([x,y]),'s':prop([w,h]),'r':prop(r),'d':1}

def layer(name,shapes=(),pivot=(0,0),rotation=None,scale=None,position=None,opacity=None,ref=None,masks=()):
    l={'ddd':0,'ind':0,'ty':0 if ref else 4,'nm':name,'sr':1,'ks':{'o':opacity or prop(100),'r':rotation or prop(0),'p':position or prop([*pivot,0]),'a':prop([*pivot,0]),'s':scale or prop([100,100,100])},'ao':0,'ip':0,'op':144,'st':0,'bm':0}
    if ref: l.update(refId=ref,w=512,h=512)
    else: l['shapes']=list(reversed(shapes))
    if masks: l['masksProperties']=list(masks); l['hasMask']=True
    return l

def mask(name,points,mode='a'):
    return {'inv':False,'mode':mode,'pt':prop(poly(points)),'o':prop(100),'x':prop(0),'nm':name}
def mapped(points): return [[round(x*450/1349+62,2),round(y*450/1349+31,2)] for x,y in points]
def bounds_center(points): return [(min(p[0] for p in points)+max(p[0] for p in points))/2,(min(p[1] for p in points)+max(p[1] for p in points))/2]
def star(x,y,r): return shape([[x,y-r],[x+r*.28,y-r*.28],[x+r,y],[x+r*.28,y+r*.28],[x,y+r],[x-r*.28,y+r*.28],[x-r,y],[x-r*.28,y-r*.28]])

def closed_eyelash(name,points,end,close_frame=None):
    x,y=bounds_center(points)
    reach=min(17,(max(p[0] for p in points)-min(p[0] for p in points))/3)
    curve={'ty':'sh','ks':prop({'v':[[x-reach,y],[x,y+2],[x+reach,y]],
        'i':[[0,0],[-3,0],[-3,1]],'o':[[3,1],[3,0],[0,0]],'c':False})}
    opacity=keys([(0,100),(3,100),(8,0),(end,0)]) if close_frame is None else keys([
        (0,0),(close_frame-3,0),(close_frame,100),(close_frame+2,100),(close_frame+6,0),(end,0)])
    return layer(name+' closed eyelash',[group('Soft closed eye',[curve],None,'#80566A',1.8)],opacity=opacity)

def load_art(source='blue-snow-maid-reference.png',static='bilipai_maid_static',size=(390,450)):
    im=Image.open(ART/source).convert('RGBA')
    im.thumbnail(size,Image.Resampling.LANCZOS)
    canvas=Image.new('RGBA',(512,512))
    canvas.alpha_composite(im,((512-im.width)//2,31))
    target=ROOT/'app/src/main/res/drawable-nodpi'/f'{static}.png'
    target.parent.mkdir(parents=True,exist_ok=True)
    canvas.save(target,optimize=True)
    image={'id':'maid_bitmap','w':512,'h':512,'u':'','p':static+'.png','e':0}
    art=layer('Blue snow maid detailed illustration',ref='maid_bitmap')
    art['ty']=2; art['ind']=1
    return [{'id':'maid_art','layers':[art]},image]

LEFT_EYE=mapped([(402,539),(416,508),(453,490),(518,491),(559,518),(555,579),(516,593),(460,593),(425,569)])
RIGHT_EYE=mapped([(620,496),(644,468),(688,460),(742,470),(775,492),(757,553),(725,568),(674,568),(639,545)])
HAND=mapped([(58,790),(68,759),(108,748),(72,702),(88,668),(131,674),(186,720),(145,664),(142,628),(163,620),(185,642),(238,716),(253,691),(280,690),(292,714),(280,771),(289,820),(267,866),(275,887),(198,915),(185,866),(142,844),(93,830),(66,813)])

HAIR_TIPS=[
    mapped([(7,1110),(68,1075),(131,1078),(160,1110),(168,1170),(120,1228),(73,1237),(3,1194)]),
    mapped([(1038,1038),(1124,1026),(1160,1088),(1140,1170),(1094,1230),(1031,1235),(995,1190)])
]


def make_welcome(art):
    kind="welcome"
    end={'welcome':60,'clean':72,'retry':144,'empty':108,'search_empty':120}[kind]
    layers=[]
    # Eye and hand patches reuse one precomposition: no duplicate image or vector payload.
    all_masks=[mask('Full illustration',[[0,0],[512,0],[512,512],[0,512]])]
    for name,points in [('Left eye',LEFT_EYE),('Right eye',RIGHT_EYE),('Greeting hand',HAND)]:
        all_masks.append(mask(name,points,'s'))
    for i,points in enumerate(HAIR_TIPS): all_masks.append(mask('Hair tip '+str(i),points,'s'))
    layers.append(layer('Maid portrait',ref='maid_art',masks=all_masks))
    for points,skin in [(LEFT_EYE,'#FFE2D3'),(RIGHT_EYE,'#FFE7DA')]:
        layers.insert(0,layer('Skin under eyelid',[group('Soft peach eyelid',[shape(points)],skin)]))
    for name,points in [('Left eye',LEFT_EYE),('Right eye',RIGHT_EYE)]:
        pivot=bounds_center(points)
        blink=[(0,[100,8,100]),(8,[100,100,100]),(end,[100,100,100])]
        if kind=='clean': blink=[(0,[100,100,100]),(46,[100,100,100]),(51,[100,4,100]),(56,[100,100,100]),(end,[100,100,100])]
        if kind in ('retry','empty','search_empty'): blink=[(0,[100,100,100]),(62,[100,100,100]),(67,[100,4,100]),(73,[100,100,100]),(end,[100,100,100])]
        layers.append(layer(name,ref='maid_art',pivot=pivot,scale=keys(blink),masks=[mask(name,points)]))
    for name,points in [('Left eye',LEFT_EYE),('Right eye',RIGHT_EYE)]:
        layers.append(closed_eyelash(name,points,end,None if kind=='welcome' else 67))
    # Gentle wrist rotation keeps the reference anatomy intact.
    rot=[(0,0),(12,-5),(24,4),(38,-3),(50,0),(end,0)]
    if kind=='clean': rot=[(0,0),(13,-6),(27,5),(40,-4),(53,0),(end,0)]
    if kind in ('retry','empty','search_empty'): rot=[(0,0),(end/2,1),(end,0)]
    layers.append(layer('Greeting hand',ref='maid_art',pivot=mapped([(235,885)])[0],rotation=keys(rot),masks=[mask('Hand and wrist',HAND)]))
    for i,points in enumerate(HAIR_TIPS):
        pivot=[bounds_center(points)[0],min(p[1] for p in points)]
        layers.append(layer('Hair tip '+str(i),ref='maid_art',pivot=pivot,
            rotation=keys([(0,0),(end*.45,1.2 if i else -1.2),(end,0)]),
            masks=[mask('Flowing hair',points)]))
    for side,(x,y) in enumerate([(152,169),(354,164)]):
        # Moving gleams and a small snow charm give the hair ornaments subtle motion.
        layers.append(layer('Ribbon snow charm '+str(side),[group('Snow glint',[star(0,0,4)],'#F8FDFF','#64CFFF',1)],position=keys([(0,[x,y,0]),(end/2,[x+(-2 if side else 2),y-2,0]),(end,[x,y,0])]),opacity=keys([(0,0),(12,70),(end-8,70),(end,0)])))
    if kind=='retry':
        layers.append(layer('Offline cloud',[
            group('Cloud',[rect(398,309,67,29,13),ellipse(384,292,31,31),ellipse(407,290,38,38)],'#EAF5FF','#7CA9C7',2),
            group('Patient cloud eyes',[ellipse(385,305,3,4),ellipse(408,305,3,4)],'#688AAB'),
            group('Connection pause',[shape([[382,334],[411,334]],False)],None,'#63B8E4',3)
        ],pivot=(398,300),position=keys([(0,[398,300,0]),(72,[398,294,0]),(end,[398,300,0])]),opacity=keys([(0,0),(14,100),(end,100)])))
    for i,(x,y) in enumerate([(87,163),(414,139),(429,236)]):
        if kind in ('retry','empty','search_empty'): break
        start=42+i*2 if kind=='clean' else 9+i*3
        layers.append(layer('Snow sparkle '+str(i),[group('Snowflake',[star(0,0,7 if i%2 else 5)],'#F9FDFF','#6BCBF1',1.5)],position=keys([(0,[x,y+6,0]),(end,[x,y-5,0])]),opacity=keys([(0,0),(start,0),(start+7,90),(end,65 if kind=='clean' else 0)])))
    layers.reverse()
    # A shared parent supplies a tiny breathing / bowing motion without re-rasterization.
    motion=layer('Character motion',pivot=(256,330)); motion['ty']=3; motion.pop('shapes',None)
    motion['ind']=len(layers)+1
    motion['ks']['p']=keys([(0,[256,332,0]),(end*.45,[256,327,0]),(end,[256,330,0])]) if kind=='welcome' else keys([(0,[256,330,0]),(end/2,[256,333,0]),(end,[256,330,0])])
    for i,l in enumerate(layers): l['ind']=i+1; l['op']=end; l['parent']=motion['ind']
    motion['op']=end; layers.append(motion)
    return {'v':'5.12.2','fr':60,'ip':0,'op':end,'w':512,'h':512,'nm':'BiliPai Blue Snow Maid '+kind,'ddd':0,'assets':copy.deepcopy(art),'layers':layers,'markers':[]}

def clean_mapped(points): return [[round(x*450/1254+31,2),round(y*450/1254+31,2)] for x,y in points]

def make_cleaning(art):
    """Closed working cycle; the shaft pivots below the fixed lower gripping hand."""
    end=96
    # Measured on this new 1254px pose, never borrowed from the completed pose.
    left=clean_mapped([(325,508),(346,493),(389,498),(426,521),(446,552),(449,587),(431,607),(394,603),(367,572)])
    right=clean_mapped([(531,523),(560,490),(607,479),(649,490),(673,513),(668,558),(643,584),(591,589),(558,569)])
    broom=clean_mapped([(532,862),(562,877),(477,983),(493,1008),(478,1041),(454,1068),(468,1130),(483,1181),(478,1221),(437,1243),(333,1244),(257,1218),(214,1187),(184,1156),(200,1118),(233,1083),(302,1045),(369,1019),(400,972),(446,979)])
    layers=[]
    # Apron/dress are solid behind the removed shaft; the bristles stand outside
    # the character silhouette so their sweep reveals genuine transparency.
    layers.append(layer('Dress behind working shaft',[group('Blue dress backing',[
        shape(clean_mapped([(431,973),(530,851),(566,870),(480,994)]))],'#37B7EF')]))
    for name,points in [('Left eye',left),('Right eye',right)]:
        layers.append(layer(name+' blink skin',[group('Eyelid skin',[shape(points)],'#FFE0D1')]))
    layers.append(layer('Working portrait',ref='maid_art',masks=[
        mask('Full working pose',[[0,0],[512,0],[512,512],[0,512]]),
        mask('Lower broom',broom,'s'),mask('Left eye',left,'s'),mask('Right eye',right,'s')]))
    # Removed eye regions have a solid skin backing, avoiding duplicate open eyes.
    for name,points in [('Left eye',left),('Right eye',right)]:
        layers.append(layer(name,ref='maid_art',pivot=bounds_center(points),masks=[mask(name,points)],
            scale=keys([(0,[100,100,100]),(61,[100,100,100]),(66,[100,4,100]),(73,[100,100,100]),(end,[100,100,100])])))
        layers.append(closed_eyelash(name,points,end,66))
    layers.append(layer('Held broom working sweep',ref='maid_art',pivot=clean_mapped([(548,864)])[0],
        masks=[mask('Connected lower shaft and bristles',broom)],
        rotation=keys([(0,0),(24,-2),(48,0),(72,2),(end,0)])))
    layers.reverse()
    motion=layer('Focused working lean',pivot=(256,365));motion['ty']=3;motion.pop('shapes',None)
    motion['ind']=len(layers)+1;motion['op']=end
    motion['ks']['r']=keys([(0,0),(24,-.4),(48,0),(72,.4),(end,0)])
    for i,l in enumerate(layers): l['ind']=i+1;l['op']=end;l['parent']=motion['ind']
    layers.append(motion)
    return {'v':'5.12.2','fr':60,'ip':0,'op':end,'w':512,'h':512,
        'nm':'BiliPai focused cleaning in progress','ddd':0,'assets':copy.deepcopy(art),'layers':layers,'markers':[]}

def make_clean(art):
    end=72
    left=clean_mapped([(387,478),(408,442),(448,443),(498,456),(529,486),(525,539),(496,565),(440,566),(412,539)])
    right=clean_mapped([(615,525),(638,492),(683,497),(735,512),(765,533),(750,583),(714,601),(664,592),(633,566)])
    broom=clean_mapped([(499,831),(540,855),(455,953),(473,995),(453,1036),(454,1150),(462,1212),(430,1253),(285,1253),(211,1226),(138,1185),(120,1140),(148,1093),(174,1060),(222,1038),(275,1002),(325,989),(339,971),(367,944),(390,939)])
    layers=[]
    for points,skin in [(left,'#FFE1D1'),(right,'#FFE1D1')]:
        layers.append(layer('Soft eyelid',[group('Peach skin',[shape(points)],skin)]))
    # White apron behind the shaft keeps the sweep from exposing a transparent gap.
    layers.append(layer('Apron behind broom',[group('Apron patch',[shape(clean_mapped([(461,872),(497,839),(528,862),(493,913),(471,930)]))],'#FAFAFF')]))
    masks=[mask('Full character',[[0,0],[512,0],[512,512],[0,512]])]
    for name,points in [('Left eye',left),('Right eye',right),('Broom',broom)]: masks.append(mask(name,points,'s'))
    layers.append(layer('Q maid holding broom',ref='maid_art',masks=masks))
    for name,points in [('Left eye',left),('Right eye',right)]:
        layers.append(layer(name,ref='maid_art',pivot=bounds_center(points),masks=[mask(name,points)],
            scale=keys([(0,[100,100,100]),(46,[100,100,100]),(51,[100,4,100]),(56,[100,100,100]),(end,[100,100,100])])))
    for name,points in [('Left eye',left),('Right eye',right)]:
        layers.append(closed_eyelash(name,points,end,51))
    layers.append(layer('Held broom sweep',ref='maid_art',pivot=clean_mapped([(516,853)])[0],masks=[mask('Broom shaft and bristles',broom)],
        rotation=keys([(0,0),(14,-6),(29,7),(42,-3),(54,0),(end,0)])))
    for i,(x,y) in enumerate([(80,459),(60,436),(119,465)]):
        layers.append(layer('Cache tile '+str(i),[group('Tile',[rect(0,0,13,13,3)],['#BDE7FA','#76CEF4','#DAF4FF'][i],'#69AED3',1)],
            position=keys([(0,[x,y,0]),(12+i*3,[x,y,0]),(32+i*3,[90,427,0]),(45+i*3,[48,392,0])]),
            rotation=keys([(0,0),(51,80)]),opacity=keys([(0,100),(26+i*4,100),(46+i*3,0),(end,0)])))
    layers.append(layer('Completion badge',[
        group('Badge',[ellipse(423,400,64,64)],'#42BCEB','#FFFFFF',4),
        group('Check',[shape([[408,400],[420,412],[441,385]],False)],None,'#FFFFFF',6)
    ],pivot=(423,400),scale=keys([(0,[95,95,100]),(44,[95,95,100]),(55,[103,103,100]),(64,[100,100,100])]),opacity=keys([(0,0),(44,0),(53,100),(end,100)])))
    for i,(x,y) in enumerate([(97,205),(427,183),(438,310)]):
        layers.append(layer('Blue snow star '+str(i),[group('Star',[star(0,0,6)],'#F8FCFF','#69CEF4',1.5)],
            position=keys([(0,[x,y+5,0]),(end,[x,y-5,0])]),opacity=keys([(0,0),(43+i*3,0),(52+i*3,100),(end,65)])))
    layers.reverse()
    motion=layer('Pleased little bow',pivot=(256,370));motion['ty']=3;motion.pop('shapes',None);motion['ind']=len(layers)+1
    motion['ks']['r']=keys([(0,0),(29,-1.2),(53,1),(end,0)])
    for i,l in enumerate(layers): l['ind']=i+1;l['op']=end;l['parent']=motion['ind']
    motion['op']=end;layers.append(motion)
    return {'v':'5.12.2','fr':60,'ip':0,'op':end,'w':512,'h':512,'nm':'BiliPai Q Maid Broom Cleanup','ddd':0,'assets':copy.deepcopy(art),'layers':layers,'markers':[]}

def make_refreshing(art):
    """Eager content-card pose; hands move with the card, no completion effects."""
    end=84
    left=clean_mapped([(403,536),(425,510),(465,504),(506,516),(542,540),(550,579),(535,599),(491,602),(448,583),(423,562)])
    right=clean_mapped([(619,470),(635,435),(674,416),(717,419),(753,439),(752,480),(732,523),(691,544),(654,525),(635,502)])
    card=clean_mapped([(422,780),(435,754),(463,734),(505,735),(775,742),(811,759),(818,784),(835,785),(851,801),(849,829),(838,848),(816,854),(813,883),(791,901),(509,894),(471,890),(462,859),(462,829),(443,827),(428,810)])
    layers=[layer('Apron behind refreshing card',[group('White apron backing',[shape(card)],'#FAFAFF')])]
    for name,points in [('Left eye',left),('Right eye',right)]:
        layers.append(layer(name+' skin backing',[group('Soft eyelid',[shape(points)],'#FFE4D7')]))
    layers.append(layer('Eager refresh portrait',ref='maid_art',masks=[
        mask('Full refresh pose',[[0,0],[512,0],[512,512],[0,512]]),
        mask('Left eye',left,'s'),mask('Right eye',right,'s'),mask('Held card and hands',card,'s')]))
    for name,points in [('Left eye',left),('Right eye',right)]:
        layers.append(layer(name,ref='maid_art',pivot=bounds_center(points),masks=[mask(name,points)],
            scale=keys([(0,[100,100,100]),(45,[100,100,100]),(50,[100,4,100]),(56,[100,100,100]),(end,[100,100,100])])))
        layers.append(closed_eyelash(name,points,end,50))
    layers.append(layer('Held fresh content card',ref='maid_art',pivot=clean_mapped([(638,819)])[0],
        masks=[mask('Both gripping hands and card',card)],
        rotation=keys([(0,0),(21,-.8),(42,0),(63,.8),(end,0)])))
    layers.reverse()
    motion=layer('Expectant refreshing lean',pivot=(256,350));motion['ty']=3;motion.pop('shapes',None)
    motion['ind']=len(layers)+1;motion['op']=end
    motion['ks']['p']=keys([(0,[256,350,0]),(42,[256,348,0]),(end,[256,350,0])])
    for i,l in enumerate(layers): l['ind']=i+1;l['op']=end;l['parent']=motion['ind']
    layers.append(motion)
    return {'v':'5.12.2','fr':60,'ip':0,'op':end,'w':512,'h':512,
        'nm':'BiliPai refreshing fresh content card','ddd':0,'assets':copy.deepcopy(art),'layers':layers,'markers':[]}


STATE_POSES={
    'retry':{
        'end':90, 'blink_frame':42,
        'eyes':[
            [[198,221],[205,214],[218,211],[231,214],[240,223],[235,240],[221,242],[207,237]],
            [[274,216],[282,209],[294,208],[308,213],[314,219],[306,233],[295,236],[281,232]]],
        'prop':'Disconnected connectors',
        'points':[[220,322],[236,315],[245,317],[249,334],[229,340],[220,335]],
        'pivot':[221,334], 'backing':'#D6EFFF', 'rotation':[(0,0),(15,-2),(30,1),(49,0),(90,0)],
        'hair':[
            [[49,401],[74,388],[96,405],[116,441],[107,451],[87,451],[65,437],[48,419]],
            [[401,412],[418,389],[449,395],[469,413],[467,443],[445,462],[422,457],[402,437]]]
    },
    'empty':{
        'end':108, 'closed_eyes':True,
        'eyes':[
            [[194,213],[204,205],[216,202],[230,204],[239,212],[233,226],[219,232],[205,226]],
            [[270,201],[280,192],[290,191],[305,195],[311,202],[303,216],[290,220],[279,214]]],
        'prop':'Held empty collection box',
        'points':[[159,354],[180,337],[208,355],[320,357],[341,338],[364,375],[342,393],[350,409],[342,439],[323,454],[301,451],[272,441],[225,440],[203,449],[182,441],[170,429],[164,411],[176,394],[187,388]],
        'pivot':[256,406], 'backing':'#F5F8FF', 'rotation':[(0,0),(20,-1),(42,1),(72,0),(108,0)],
        'hair':[
            [[47,394],[72,382],[91,398],[105,425],[93,440],[66,437],[49,416]],
            [[413,394],[434,382],[466,394],[471,420],[455,443],[431,447],[409,431]]]
    },
    'search_empty':{
        'end':120, 'static_prop':True, 'blink_frame':82,
        'eyes':[
            [[191,220],[199,211],[214,207],[231,208],[244,220],[240,239],[227,249],[211,246],[198,237]],
            [[286,212],[294,203],[306,199],[317,200],[327,206],[321,219],[307,228],[293,226]]],
        'prop':'Held looking glass',
        'points':[[161,213],[180,212],[198,221],[208,235],[210,251],[202,267],[193,276],[198,283],[206,291],[210,307],[219,333],[211,343],[207,362],[176,363],[174,341],[170,332],[162,313],[162,300],[170,285],[179,281],[167,280],[149,272],[139,260],[137,244],[142,226]],
        'pivot':[190,356], 'backing':'#DCEFFF', 'rotation':[(0,0),(25,-1.3),(53,1),(88,0),(120,0)],
        'hair':[
            [[48,392],[73,380],[95,398],[109,429],[96,447],[67,450],[48,432]],
            [[405,415],[418,394],[447,389],[467,409],[467,439],[448,462],[424,459],[407,441]]]
    }
}

STATE_POSES.update({
    'favorite':{
        'end':72, 'blink_frame':53, 'eye_names':['Right'],
        'eyes':[[[271,183],[278,177],[289,175],[301,178],[308,187],[304,199],[292,204],[280,199]]],
        'prop':'Held favorite star',
        'points':[[169,322],[207,306],[216,282],[226,255],[238,249],[253,255],[275,276],[284,286],[327,282],[346,287],[354,301],[345,325],[335,343],[345,350],[353,371],[351,398],[341,409],[301,404],[281,399],[249,393],[224,395],[196,399],[190,389],[193,368],[196,349],[179,345],[169,334]],
        'pivot':[257,356], 'backing':'#F6FAFF', 'rotation':[(0,0),(22,-.7),(44,.5),(72,0)],
        'scale':[(0,[100,100,100]),(25,[101.5,101.5,100]),(45,[100,100,100]),(72,[100,100,100])],
        'hair':[
            [[48,389],[71,378],[94,395],[110,427],[95,447],[68,449],[48,430]],
            [[408,404],[424,385],[455,391],[469,411],[462,437],[443,456],[421,450],[405,430]]]
    },
    'download':{
        'end':72, 'blink_frame':51,
        'eyes':[
            [[204,194],[211,185],[224,184],[236,189],[242,198],[235,209],[221,216],[212,208]],
            [[276,179],[285,169],[296,170],[307,177],[310,186],[301,198],[289,201],[281,193]]],
        'prop':'Thumbs up hand',
        'points':[[145,215],[155,212],[162,221],[166,237],[178,244],[183,255],[181,268],[178,282],[166,292],[147,298],[137,290],[135,274],[130,264],[138,247],[144,238]],
        'pivot':[148,293], 'backing':'#E5F4FF', 'rotation':[(0,0),(15,-2.5),(30,1.5),(44,0),(72,0)],
        'hair':[
            [[49,393],[73,381],[97,397],[108,430],[94,449],[67,449],[48,430]],
            [[408,397],[424,380],[456,389],[471,414],[462,439],[443,450],[422,445],[404,427]]]
    }
})

def make_state(kind,art):
    config=STATE_POSES[kind];end=config['end'];eyes=[] if config.get('closed_eyes') else config['eyes']
    moving_prop=not config.get('static_prop')
    prop_points=config['points']
    layers=[]
    # Small backing patches prevent cutout gaps when the held prop pivots.
    if moving_prop:
        layers.append(layer('Clothing behind prop',[group('Backing',[shape(prop_points)],config['backing'])]))
    for i,points in enumerate(eyes):
        layers.append(layer('Skin behind eye '+str(i),[group('Peach eyelid',[shape(points)],'#FFE7DA')]))
    masks=[mask('Full state pose',[[0,0],[512,0],[512,512],[0,512]])]
    for i,points in enumerate(eyes):masks.append(mask('Eye '+str(i),points,'s'))
    if moving_prop:masks.append(mask('Held prop',prop_points,'s'))
    for i,points in enumerate(config['hair']):masks.append(mask('Hair tip '+str(i),points,'s'))
    layers.append(layer('Distinct '+kind+' pose' if moving_prop else config['prop'],ref='maid_art',masks=masks))
    if moving_prop:
        layers.append(layer(config['prop'],ref='maid_art',pivot=config['pivot'],masks=[mask('Hand and prop',prop_points)],rotation=keys(config['rotation']),scale=keys(config['scale']) if 'scale' in config else None))
    close=config.get('blink_frame',67)
    for i,points in enumerate(eyes):
        name=config.get('eye_names',['Left','Right'])[i]+' eye'
        layers.append(layer(name,ref='maid_art',pivot=bounds_center(points),masks=[mask(name,points)],
            scale=keys([(0,[100,100,100]),(close-5,[100,100,100]),(close,[100,4,100]),(close+6,[100,100,100]),(end,[100,100,100])])))
        layers.append(closed_eyelash(name,points,end,close))
    for i,points in enumerate(config['hair']):
        pivot=[bounds_center(points)[0],min(p[1] for p in points)]
        layers.append(layer('Hair tip '+str(i),ref='maid_art',pivot=pivot,masks=[mask('Hair',points)],
            rotation=keys([(0,0),(end*.4,-.9 if i==0 else .9),(end,0)])))
    if kind=='retry':
        layers.append(layer('Disconnected gap hint',[group('Paused connection',[shape([[256,325],[269,325]],False)],None,'#6CA6CB',2)],
            opacity=keys([(0,0),(16,0),(27,75),(40,0),(end,0)])))
    elif kind=='empty':
        layers.append(layer('Empty box glint',[group('Snow glint',[star(0,0,3)],'#FFFFFF')],
            position=keys([(0,[240,417,0]),(32,[240,417,0]),(54,[273,421,0]),(end,[273,421,0])]),
            opacity=keys([(0,0),(32,0),(42,65),(54,0),(end,0)])))
    elif kind=='favorite':
        layers.append(layer('Favorite star shimmer',[group('Star shimmer',[star(0,0,6)],'#FFFFFF','#FFE69A',1)],
            position=keys([(0,[254,306,0]),(end,[261,298,0])]),opacity=keys([(0,0),(16,0),(28,90),(44,0),(end,0)])))
    elif kind=='download':
        layers.append(layer('Saved video check pulse',[group('Completion ring',[ellipse(0,0,36,36)],None,'#6FCBEE',2)],
            pivot=(0,0),position=prop([364,387,0]),scale=keys([(0,[90,90,100]),(20,[90,90,100]),(37,[118,118,100]),(end,[125,125,100])]),
            opacity=keys([(0,0),(20,0),(29,70),(48,0),(end,0)])))
    else:
        layers.append(layer('Lens inspection glint',[group('Glass glint',[ellipse(0,0,3,8)],'#FFFFFF')],
            position=keys([(0,[195,207,0]),(22,[195,207,0]),(46,[237,201,0]),(end,[237,201,0])]),
            opacity=keys([(0,0),(22,0),(31,65),(46,0),(end,0)])))
    layers.reverse()
    motion=layer('State breathing and head tilt',pivot=(256,300));motion['ty']=3;motion.pop('shapes',None);motion['ind']=len(layers)+1
    motion['ks']['p']=keys([(0,[256,300,0]),(end*.5,[256,302,0]),(end,[256,300,0])])
    motion['ks']['r']=keys([(0,0),(end*.4,.4 if kind=='retry' else -.4),(end,0)])
    for i,l in enumerate(layers):l['ind']=i+1;l['op']=end;l['parent']=motion['ind']
    motion['op']=end;layers.append(motion)
    return {'v':'5.12.2','fr':60,'ip':0,'op':end,'w':512,'h':512,'nm':'BiliPai distinct '+kind+' pose','ddd':0,'assets':copy.deepcopy(art),'layers':layers,'markers':[]}


def make_follow_feedback(kind,art):
    """Independent measured expressions and gestures for follow and unfollow."""
    following=kind=='follow'
    end=72 if following else 60
    if following:
        eyes=[clean_mapped([(450,458),(469,427),(505,416),(542,429),(562,451),(558,490),(536,513),(495,516),(468,493)]),
              clean_mapped([(657,412),(674,382),(710,368),(750,380),(770,402),(761,444),(734,470),(693,467),(667,441)])]
        hand=clean_mapped([(510,857),(530,817),(581,765),(637,740),(655,749),(690,738),(705,750),(690,779),(718,776),(722,790),(697,811),(684,832),(649,852),(581,884),(545,891)])
        pivot=clean_mapped([(535,866)])[0]
        hair=[clean_mapped([(72,936),(111,912),(160,982),(201,1058),(180,1116),(124,1115),(71,1065)]),
              clean_mapped([(1050,920),(1090,935),(1207,935),(1222,1015),(1204,1084),(1176,1143),(1127,1119),(1085,1034)])]
    else:
        eyes=[] # Already closed: preserve the drawn lashes without fake blinking.
        hand=clean_mapped([(645,1109),(704,1100),(764,1112),(813,1122),(848,1145),(850,1179),(829,1211),(763,1231),(693,1228),(676,1213),(697,1177),(650,1172),(627,1151)])
        pivot=clean_mapped([(653,1145)])[0]
        hair=[clean_mapped([(34,944),(94,928),(143,1008),(196,1077),(187,1131),(128,1160),(64,1093),(25,1026)]),
              clean_mapped([(1090,936),(1140,940),(1223,929),(1241,1000),(1219,1075),(1179,1147),(1119,1122),(1088,1050)])]
    layers=[]
    # Tiny hand movement is backed by the garment/skin rather than transparency.
    layers.append(layer('Backing under grateful hand' if following else 'Apron under resting hands',
        [group('Soft backing',[shape(hand)],'#FFE4D7' if following else '#FAFAFF')]))
    for points in eyes:
        layers.append(layer('Skin behind grateful eye',[group('Soft skin',[shape(points)],'#FFE5D8')]))
    masks=[mask('Full independent pose',[[0,0],[512,0],[512,512],[0,512]]),mask('Gesture hand',hand,'s')]
    for i,points in enumerate(eyes): masks.append(mask('Eye '+str(i),points,'s'))
    for i,points in enumerate(hair): masks.append(mask('Hair tip '+str(i),points,'s'))
    layers.append(layer('Joyful thank you portrait' if following else 'Calm farewell portrait',ref='maid_art',masks=masks))
    for i,points in enumerate(eyes):
        name=['Left','Right'][i]+' eye'
        layers.append(layer(name,ref='maid_art',pivot=bounds_center(points),masks=[mask(name,points)],
            scale=keys([(0,[100,100,100]),(39,[100,100,100]),(44,[100,4,100]),(50,[100,100,100]),(end,[100,100,100])])))
        layers.append(closed_eyelash(name,points,end,44))
    layers.append(layer('Grateful chest hand' if following else 'Quiet joined hands',ref='maid_art',pivot=pivot,
        masks=[mask('Own gesture hand',hand)],
        rotation=keys([(0,0),(20,.5 if following else -.35),(40,0),(end,0)])))
    for i,points in enumerate(hair):
        layers.append(layer('Hair tip '+str(i),ref='maid_art',pivot=[bounds_center(points)[0],min(p[1] for p in points)],
            masks=[mask('Measured hair tip',points)],rotation=keys([(0,0),(end*.4,-.5 if i==0 else .5),(end,0)])))
    layers.reverse()
    motion=layer('Happy grateful bow' if following else 'Quiet farewell nod',pivot=(256,430))
    motion['ty']=3;motion.pop('shapes',None);motion['ind']=len(layers)+1;motion['op']=end
    motion['ks']['p']=keys([(0,[256,430,0]),(end*.35,[256,434 if following else 432,0]),(end*.7,[256,430,0]),(end,[256,430,0])])
    motion['ks']['r']=keys([(0,0),(end*.35,.6 if following else -.35),(end*.7,0),(end,0)])
    for i,l in enumerate(layers): l['ind']=i+1;l['op']=end;l['parent']=motion['ind']
    layers.append(motion)
    return {'v':'5.12.2','fr':60,'ip':0,'op':end,'w':512,'h':512,
        'nm':'BiliPai '+('happy follow gratitude' if following else 'quiet unfollow farewell'),
        'ddd':0,'assets':copy.deepcopy(art),'layers':layers,'markers':[]}

def five_star(x,y,r):
    return shape([[x+math.cos(-math.pi/2+i*math.pi/5)*(r if i%2==0 else r*.43),
                   y+math.sin(-math.pi/2+i*math.pi/5)*(r if i%2==0 else r*.43)] for i in range(10)])

def make_triple(art):
    end=108
    fists=[
        [[108,220],[112,215],[122,211],[132,212],[141,219],[143,227],[140,239],[131,246],[120,245],[111,238],[106,231]],
        [[328,249],[335,241],[346,241],[354,247],[360,255],[357,266],[351,274],[340,276],[329,269],[325,258]]]
    hair=[
        [[54,344],[78,336],[98,353],[109,381],[93,398],[70,399],[53,380]],
        [[405,346],[427,335],[460,348],[473,372],[462,392],[440,402],[418,397],[404,377]]]
    layers=[]
    for i,points in enumerate(fists):
        layers.append(layer('Hair behind fist '+str(i),[group('Backing',[shape(points)],'#EDF7FF')]))
    masks=[mask('Full celebrating maid',[[0,0],[512,0],[512,512],[0,512]])]
    for i,points in enumerate(fists):masks.append(mask('Fist '+str(i),points,'s'))
    for i,points in enumerate(hair):masks.append(mask('Hair '+str(i),points,'s'))
    layers.append(layer('Joyful closed eyes and laughing pose',ref='maid_art',masks=masks))
    for i,points in enumerate(fists):
        layers.append(layer('Celebration fist '+str(i),ref='maid_art',pivot=(123,245) if i==0 else (341,274),
            rotation=keys([(0,0),(20,-3 if i==0 else 3),(38,2 if i==0 else -2),(60,0),(end,0)]),masks=[mask('Closed fist',points)]))
    for i,points in enumerate(hair):
        layers.append(layer('Jumping hair tip '+str(i),ref='maid_art',pivot=(bounds_center(points)[0],min(p[1] for p in points)),
            rotation=keys([(0,0),(27,-1.6 if i==0 else 1.6),(48,.6 if i==0 else -.6),(end,0)]),masks=[mask('Hair',points)]))
    layers.reverse()
    motion=layer('Double fist happy hop',pivot=(256,450));motion['ty']=3;motion.pop('shapes',None);motion['ind']=len(layers)+1
    motion['ks']['p']=keys([(0,[256,450,0]),(12,[256,454,0]),(27,[256,435,0]),(45,[256,450,0]),(58,[256,447,0]),(72,[256,450,0]),(end,[256,450,0])])
    motion['ks']['s']=keys([(0,[100,100,100]),(12,[101,98.5,100]),(27,[99,101,100]),(45,[101,99,100]),(58,[100,100,100]),(end,[100,100,100])])
    for i,l in enumerate(layers):l['ind']=i+1;l['op']=end;l['parent']=motion['ind']
    motion['op']=end;layers.append(motion)
    # Three separate local vector badges: activate only after the real three-action success.
    badge_shapes=[
        [group('Like thumb',[shape([[-12,10],[-12,-2],[-6,-2],[-2,-12],[2,-12],[3,-4],[11,-4],[13,0],[10,12],[-5,12],[-6,10]])],'#FFFFFF')],
        [group('Coin',[ellipse(0,0,24,24)],'#FFFFFF','#E2E8EF',1.5),group('Coin slot',[rect(0,0,5,12,2)],'#B9C7D5')],
        [group('Favorite star',[five_star(0,0,13)],'#FFEAA2','#FFFFFF',1.5)]]
    for i,shapes in enumerate(badge_shapes):
        t=32+i*10
        badge=layer(['Like success badge','Coin success badge','Favorite success badge'][i],
            [group('Blue badge',[ellipse(0,0,43,43)],'#42BDEB','#FFFFFF',2)]+shapes,pivot=(0,0),
            position=keys([(0,[142+i*114,490,0]),(t,[142+i*114,490,0]),(t+10,[142+i*114,480,0]),(end,[142+i*114,480,0])]),
            scale=keys([(0,[80,80,100]),(t,[80,80,100]),(t+9,[106,106,100]),(t+16,[100,100,100]),(end,[100,100,100])]),
            opacity=keys([(0,0),(t,0),(t+7,100),(end,100)]))
        badge['ind']=len(layers)+1;badge['op']=end;layers.insert(0,badge)
    return {'v':'5.12.2','fr':60,'ip':0,'op':end,'w':512,'h':512,'nm':'BiliPai triple success happy hop','ddd':0,'assets':copy.deepcopy(art),'layers':layers,'markers':[]}

if __name__=='__main__':
    art=load_art(); animations={}
    for kind,name in [('welcome','bilipai_maid_welcome'),('clean','bilipai_maid_clean_complete'),('cleaning','bilipai_maid_cleaning'),('retry','bilipai_maid_retry'),('empty','bilipai_maid_empty'),('search_empty','bilipai_maid_search_empty'),('favorite','bilipai_maid_favorite_saved'),('follow','bilipai_maid_follow_success'),('unfollow','bilipai_maid_unfollow_complete'),('download','bilipai_maid_download_complete'),('triple','bilipai_maid_triple_success')]:
        if kind=='clean':
            data=make_clean(load_art('blue-snow-maid-clean-reference.png','bilipai_maid_clean_static',(450,450)))
        elif kind=='cleaning':
            data=make_cleaning(load_art('blue-snow-maid-cleaning-reference.png','bilipai_maid_cleaning_static',(450,450)))
        elif kind in ('follow','unfollow'):
            source='blue-snow-maid-follow-happy-reference.png' if kind=='follow' else 'blue-snow-maid-unfollow-reference.png'
            data=make_follow_feedback(kind,load_art(source,'bilipai_maid_'+kind+'_static',(450,450)))
        elif kind=='triple':
            data=make_triple(load_art('blue-snow-maid-triple-reference.png','bilipai_maid_triple_static',(450,450)))
        elif kind=='welcome':
            data=make_welcome(art)
        else:
            pose_art=load_art('blue-snow-maid-'+kind.replace('_','-')+'-reference.png','bilipai_maid_'+kind+'_static',(450,450))
            data=make_state(kind,pose_art)
        animations[name]=data
        (ROOT/'app/src/main/res/raw'/f'{name}.json').write_text(json.dumps(data,separators=(',',':'))+'\n')
    build_preview()
    print('Generated eleven local layered Lotties and matching static fallbacks.')
